name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ github.sha }}
        env:
          CR_PAT: ${{ secrets.CR_PAT }}
          DOCKER_AUTH_CONFIG: '{"auths":{"ghcr.io":{"username":"${{ github.repository_owner }}","password":"${{ secrets.CR_PAT }}"}}}'
