name: Docker Build

on:
  push:
    branches:
      - main  # Adjust the branch name as per your needs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/thiagogpa/schedule_builder_bot:latest
        env:
          CR_PAT: ${{ secrets.GITHUB_TOKEN }}
