name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Show directory contents
        run: ls -la        

      - name: Build and push Docker image
        run: docker buildx build --push --tag ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest -f Dockerfile .
